// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.opencaption.opencaption

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object EnginePigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class EngineConfig (
  val asrPath: String,
  val vadPath: String,
  val translationPath: String,
  val mode: String,
  val threads: Long,
  val names: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EngineConfig {
      val asrPath = pigeonVar_list[0] as String
      val vadPath = pigeonVar_list[1] as String
      val translationPath = pigeonVar_list[2] as String
      val mode = pigeonVar_list[3] as String
      val threads = pigeonVar_list[4] as Long
      val names = pigeonVar_list[5] as String
      return EngineConfig(asrPath, vadPath, translationPath, mode, threads, names)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      asrPath,
      vadPath,
      translationPath,
      mode,
      threads,
      names,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EngineConfig
    return EnginePigeonUtils.deepEquals(this.asrPath, other.asrPath) && EnginePigeonUtils.deepEquals(this.vadPath, other.vadPath) && EnginePigeonUtils.deepEquals(this.translationPath, other.translationPath) && EnginePigeonUtils.deepEquals(this.mode, other.mode) && EnginePigeonUtils.deepEquals(this.threads, other.threads) && EnginePigeonUtils.deepEquals(this.names, other.names)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EnginePigeonUtils.deepHash(this.asrPath)
    result = 31 * result + EnginePigeonUtils.deepHash(this.vadPath)
    result = 31 * result + EnginePigeonUtils.deepHash(this.translationPath)
    result = 31 * result + EnginePigeonUtils.deepHash(this.mode)
    result = 31 * result + EnginePigeonUtils.deepHash(this.threads)
    result = 31 * result + EnginePigeonUtils.deepHash(this.names)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecognitionEvent (
  val epoch: Long,
  val window: Long,
  val revision: Long,
  val startMs: Long,
  val endMs: Long,
  val text: String,
  val finalResult: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecognitionEvent {
      val epoch = pigeonVar_list[0] as Long
      val window = pigeonVar_list[1] as Long
      val revision = pigeonVar_list[2] as Long
      val startMs = pigeonVar_list[3] as Long
      val endMs = pigeonVar_list[4] as Long
      val text = pigeonVar_list[5] as String
      val finalResult = pigeonVar_list[6] as Boolean
      return RecognitionEvent(epoch, window, revision, startMs, endMs, text, finalResult)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      epoch,
      window,
      revision,
      startMs,
      endMs,
      text,
      finalResult,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RecognitionEvent
    return EnginePigeonUtils.deepEquals(this.epoch, other.epoch) && EnginePigeonUtils.deepEquals(this.window, other.window) && EnginePigeonUtils.deepEquals(this.revision, other.revision) && EnginePigeonUtils.deepEquals(this.startMs, other.startMs) && EnginePigeonUtils.deepEquals(this.endMs, other.endMs) && EnginePigeonUtils.deepEquals(this.text, other.text) && EnginePigeonUtils.deepEquals(this.finalResult, other.finalResult)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EnginePigeonUtils.deepHash(this.epoch)
    result = 31 * result + EnginePigeonUtils.deepHash(this.window)
    result = 31 * result + EnginePigeonUtils.deepHash(this.revision)
    result = 31 * result + EnginePigeonUtils.deepHash(this.startMs)
    result = 31 * result + EnginePigeonUtils.deepHash(this.endMs)
    result = 31 * result + EnginePigeonUtils.deepHash(this.text)
    result = 31 * result + EnginePigeonUtils.deepHash(this.finalResult)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BilingualEvent (
  val epoch: Long,
  val window: Long,
  val startMs: Long,
  val endMs: Long,
  val english: String,
  val chinese: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BilingualEvent {
      val epoch = pigeonVar_list[0] as Long
      val window = pigeonVar_list[1] as Long
      val startMs = pigeonVar_list[2] as Long
      val endMs = pigeonVar_list[3] as Long
      val english = pigeonVar_list[4] as String
      val chinese = pigeonVar_list[5] as String
      return BilingualEvent(epoch, window, startMs, endMs, english, chinese)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      epoch,
      window,
      startMs,
      endMs,
      english,
      chinese,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BilingualEvent
    return EnginePigeonUtils.deepEquals(this.epoch, other.epoch) && EnginePigeonUtils.deepEquals(this.window, other.window) && EnginePigeonUtils.deepEquals(this.startMs, other.startMs) && EnginePigeonUtils.deepEquals(this.endMs, other.endMs) && EnginePigeonUtils.deepEquals(this.english, other.english) && EnginePigeonUtils.deepEquals(this.chinese, other.chinese)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + EnginePigeonUtils.deepHash(this.epoch)
    result = 31 * result + EnginePigeonUtils.deepHash(this.window)
    result = 31 * result + EnginePigeonUtils.deepHash(this.startMs)
    result = 31 * result + EnginePigeonUtils.deepHash(this.endMs)
    result = 31 * result + EnginePigeonUtils.deepHash(this.english)
    result = 31 * result + EnginePigeonUtils.deepHash(this.chinese)
    return result
  }
}
private open class EnginePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EngineConfig.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecognitionEvent.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BilingualEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EngineConfig -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RecognitionEvent -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BilingualEvent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface EngineHost {
  fun requestMicrophone(callback: (Result<Boolean>) -> Unit)
  fun prepare(config: EngineConfig, callback: (Result<Unit>) -> Unit)
  fun start(epoch: Long)
  fun pause()
  fun drain(callback: (Result<Unit>) -> Unit)
  fun cancel()
  /** Replace the bounded E2E hint string between audio windows. */
  fun updateHints(hints: String)
  fun release(callback: (Result<Unit>) -> Unit)
  fun translate(epoch: Long, id: String, text: String, payload: String, callback: (Result<String>) -> Unit)
  fun cancelTranslation(id: String)
  fun mlKitReady(callback: (Result<Boolean>) -> Unit)
  fun downloadMlKit(callback: (Result<Unit>) -> Unit)
  fun deleteMlKit(callback: (Result<Unit>) -> Unit)
  fun openAppSettings()

  companion object {
    /** The codec used by EngineHost. */
    val codec: MessageCodec<Any?> by lazy {
      EnginePigeonCodec()
    }
    /** Sets up an instance of `EngineHost` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: EngineHost?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.requestMicrophone$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.requestMicrophone{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.prepare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as EngineConfig
            api.prepare(configArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonUtils.wrapError(error))
              } else {
                reply.reply(EnginePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val epochArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.start(epochArg)
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.pause$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pause()
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.drain$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.drain{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonUtils.wrapError(error))
              } else {
                reply.reply(EnginePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.cancel()
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.updateHints$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val hintsArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.updateHints(hintsArg)
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.release$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.release{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonUtils.wrapError(error))
              } else {
                reply.reply(EnginePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.translate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val epochArg = args[0] as Long
            val idArg = args[1] as String
            val textArg = args[2] as String
            val payloadArg = args[3] as String
            api.translate(epochArg, idArg, textArg, payloadArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.cancelTranslation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val idArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancelTranslation(idArg)
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.mlKitReady$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.mlKitReady{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(EnginePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.downloadMlKit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.downloadMlKit{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonUtils.wrapError(error))
              } else {
                reply.reply(EnginePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.deleteMlKit$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.deleteMlKit{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(EnginePigeonUtils.wrapError(error))
              } else {
                reply.reply(EnginePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.opencaption.EngineHost.openAppSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openAppSettings()
              listOf(null)
            } catch (exception: Throwable) {
              EnginePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class EngineEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by EngineEvents. */
    val codec: MessageCodec<Any?> by lazy {
      EnginePigeonCodec()
    }
  }
  fun recognition(eventArg: RecognitionEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.opencaption.EngineEvents.recognition$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(EnginePigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun bilingual(eventArg: BilingualEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.opencaption.EngineEvents.bilingual$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(EnginePigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun activity(epochArg: Long, levelArg: Double, speechArg: Boolean, audioMsArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.opencaption.EngineEvents.activity$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(epochArg, levelArg, speechArg, audioMsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(EnginePigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun interrupted(epochArg: Long, codeArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.opencaption.EngineEvents.interrupted$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(epochArg, codeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(EnginePigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun gap(epochArg: Long, startMsArg: Long, endMsArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.opencaption.EngineEvents.gap$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(epochArg, startMsArg, endMsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(EnginePigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun diagnostic(epochArg: Long, codeArg: String, durationMsArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.opencaption.EngineEvents.diagnostic$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(epochArg, codeArg, durationMsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(EnginePigeonUtils.createConnectionError(channelName)))
      }
    }
  }
}
